log:0919
==

# h5py

h5pyパッケージは、HDF5バイナリデータフォーマットに対するPythonのインターフェイス

今回は[iPython](https://qiita.com/5t111111/items/7852e13ace6de288042f)と併用して使った

[こちら](https://www.aipacommander.com/entry/2017/05/23/191915)を参照した

読み書きを同時にするときはオプション"a"

# MobileNet-SSDのモデル用コードのデバッグ（獄）

wh_listの決定部分を公開実装のやり方に変更してみると、推論自体は走る

![](https://i.imgur.com/tNcfFCo.png)

h5のキーだけ取り出したものがこちら
```
['activation_14',
 'activation_15',
 'activation_16',
 'activation_17',
 'activation_18',
 'activation_19',
 'activation_20',
 'activation_21',
 'activation_22',
 'activation_23',
 'activation_24',
 'activation_25',
 'activation_26',
 'bn11',
 'bn12',
 'bn12dw',
 'bn13',
 'bn13dw',
 'bn14_1',
 'bn14_2',
 'bn15_1',
 'bn15_2',
 'bn16_1',
 'bn16_2',
 'bn17_1',
 'bn17_2',
 'conv11',
 'conv11_mbox_conf',
 'conv11_mbox_conf_flat',
 'conv11_mbox_loc',
 'conv11_mbox_loc_flat',
 'conv11_mbox_priorbox',
 'conv12',
 'conv12dw',
 'conv13',
 'conv13_mbox_conf',
 'conv13_mbox_conf_flat',
 'conv13_mbox_loc',
 'conv13_mbox_loc_flat',
 'conv13_mbox_priorbox',
 'conv13dw',
 'conv14_1',
 'conv14_2',
 'conv14_2_mbox_conf',
 'conv14_2_mbox_conf_flat',
 'conv14_2_mbox_loc',
 'conv14_2_mbox_loc_flat',
 'conv14_2_mbox_priorbox',
 'conv15_1',
 'conv15_2',
 'conv15_2_mbox_conf',
 'conv15_2_mbox_conf_flat',
 'conv15_2_mbox_loc',
 'conv15_2_mbox_loc_flat',
 'conv15_2_mbox_priorbox',
 'conv16_1',
 'conv16_2',
 'conv16_2_mbox_conf',
 'conv16_2_mbox_conf_flat',
 'conv16_2_mbox_loc',
 'conv16_2_mbox_loc_flat',
 'conv16_2_mbox_priorbox',
 'conv17_1',
 'conv17_2',
 'conv17_2_mbox_conf',
 'conv17_2_mbox_conf_flat',
 'conv17_2_mbox_loc',
 'conv17_2_mbox_loc_flat',
 'conv17_2_mbox_priorbox',
 'input_3',
 'mbox_conf',
 'mbox_conf_final',
 'mbox_conf_logits',
 'mbox_loc',
 'mbox_loc_final',
 'mbox_priorbox',
 'model_3',
 'predictions']
```

stepsの値が間違っていたみたいで、修正したらジュピターでやったものと同じ結果が出ました

![](https://i.imgur.com/IDjIair.png)

### 学習用スクリプトの作成

現状としては１epoch目の最初に以下のようなエラーが出ています

```
Traceback (most recent call last):
  File "mobilenet_ssd_training_pascal.py", line 279, in <module>
    initial_epoch=initial_epoch)
  File "/opt/conda/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/opt/conda/lib/python3.5/site-packages/keras/engine/training_generator.py", line 191, in fit_generator
    class_weight=class_weight)
  File "/opt/conda/lib/python3.5/site-packages/keras/engine/training.py", line 1220, in train_on_batch
    outputs = self.train_function(ins)
  File "/opt/conda/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2661, in __call__
    return self._call(inputs)
  File "/opt/conda/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2631, in _call
    fetched = self._callable_fn(*array_vals)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1382, in __call__
    run_metadata_ptr)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [8,2278,4] vs. [8,1917,4]
         [[Node: loss/predictions_loss/sub_1 = Sub[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/AddN_1"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](loss/predictions_loss/strided_slice_4, loss/predictions_loss/strided_slice_5)]]
         [[Node: loss/predictions_loss/count_nonzero/ToInt64/_2921 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_6979_loss/predictions_loss/count_nonzero/ToInt64", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

- predictor_sizes比較

現mobilenet-ssd
```
[array([19, 19]), array([10, 10]), array([5, 5]), array([3, 3]), array([2, 2]), array([1, 1])]
```
ssd_keras
```
[array([38, 38]), array([19, 19]), array([10, 10]), array([5, 5]), array([3, 3]), array([1, 1])]
```

- feature_mapで比較（[batch_size, feature_map_channels, feature_map_height, feature_map_width]）で比較

現mobilenet-ssd
```
[None, 512, 19, 19]
[None, 1024, 10, 10]
[None, 512, 5, 5]
[None, 256, 3, 3]
[None, 256, 2, 2]
[None, 128, 1, 1]
```

ssd_keras
```
[None, 16, 38, 38]
[None, 24, 19, 19]
[None, 24, 10, 10]
[None, 24, 5, 5]
[None, 24, 3, 3]
[None, 24, 1, 1]
```

- 一周回って最初の見立てで合ってた

- 具体的には、ssd_input_encoderの中で、一つ目のpredictor_layerにだけtwo_boxes_for_ar1の影響を受けないようにしている

# Git

- コミットメッセージを変更するときは

```
$ git commit --amend -m <コミットメッセージ>
```

# Keras

- もう実装読めよ！つ（[GitHub](https://github.com/keras-team/keras)）